version: "3"

services:
  auth_api:
    container_name: Auth_API
    build:
      context: ./../
      dockerfile: ./src/Authentication.Api/Dockerfile
    env_file: .env
    ports:
      - 81:80
      - 444:443